"""Generate the crate example (02-crate): the same box twice.

  crate_starved.obj  the lid island packed at 1/3 the scale of the
                     others — the classic "shrank it to make room and
                     forgot to re-balance" edit. Density spread 3.0x.
  crate_fixed.obj    the lid island restored to full scale (the fix the
                     density finding asks for, applied).

Run: python make_crate.py
"""

from __future__ import annotations

from pathlib import Path

HERE = Path(__file__).parent / "02-crate"

S = 50.0                                    # a 50 mm crate
FACES3 = [
    [(0, 0, 0), (S, 0, 0), (S, S, 0), (0, S, 0)],       # front
    [(S, 0, S), (0, 0, S), (0, S, S), (S, S, S)],       # back
    [(S, 0, 0), (S, 0, S), (S, S, S), (S, S, 0)],       # right
    [(0, 0, S), (0, 0, 0), (0, S, 0), (0, S, S)],       # left
    [(0, S, 0), (S, S, 0), (S, S, S), (0, S, S)],       # top (the lid)
    [(0, 0, S), (S, 0, S), (S, 0, 0), (0, 0, 0)],       # bottom
]
SLOTS = [(0.02, 0.02), (0.35, 0.02), (0.68, 0.02),
         (0.02, 0.35), (0.35, 0.35), (0.68, 0.35)]


def build(starved: bool) -> str:
    lines = ["# generated by examples/make_crate.py", "usemtl crate"]
    verts, uvs, faces = [], [], []
    for i, (f3, (ox, oy)) in enumerate(zip(FACES3, SLOTS)):
        s = 0.10 if (starved and i == 4) else 0.30
        vi, ti = [], []
        for c in f3:
            verts.append(c)
            vi.append(len(verts))
        for qu, qv in [(0, 0), (1, 0), (1, 1), (0, 1)]:
            uvs.append((ox + qu * s, oy + qv * s))
            ti.append(len(uvs))
        faces.append((vi, ti))
    for v in verts:
        lines.append(f"v {v[0]} {v[1]} {v[2]}")
    for t in uvs:
        lines.append(f"vt {t[0]:.6f} {t[1]:.6f}")
    for vi, ti in faces:
        lines.append("f " + " ".join(f"{a}/{b}" for a, b in zip(vi, ti)))
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    HERE.mkdir(parents=True, exist_ok=True)
    (HERE / "crate_starved.obj").write_text(build(True), encoding="utf-8")
    (HERE / "crate_fixed.obj").write_text(build(False), encoding="utf-8")
    print(f"wrote 2 crates to {HERE}")
