"""Generate the example assets, with defects of known magnitude.

Same principle as animationsight's clips: a real asset has unknown
defects, so it can only show that the tool says *something*. Here the
answer key is in this file.

  cube_clean.obj      6 quads, one island per face, uniform texel density
  cube_broken.obj     the same cube with, exactly:
                        * face 2's UV winding flipped
                        * face 3's island scaled to 1/3 (3x less density)
                        * face 4 stretched 4:1 in u
                        * face 5 moved outside the 0..1 square
  tile_clean.png      a texture that genuinely tiles (trig, periodic)
  tile_seam.png       the same texture with the right/bottom edges darkened
  normal_ok.png       a valid tangent-space normal map
  normal_bad.png      the same, mangled: not unit length, sRGB'd
  rough_banded.png    a roughness map quantised to 6 levels

Run: python make_assets.py
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np
from PIL import Image

HERE = Path(__file__).parent / "01-cube"
SIZE = 256

# A cube with one UV island per face, each a 0.32 square in a 2x3 grid.
CORNERS = [
    # (name, origin, u_dir, v_dir) — each face's 3D frame, 1 unit square
    ("front", (0, 0, 0), (1, 0, 0), (0, 1, 0)),
    ("back", (1, 0, 1), (-1, 0, 0), (0, 1, 0)),
    ("right", (1, 0, 0), (0, 0, 1), (0, 1, 0)),
    ("left", (0, 0, 1), (0, 0, -1), (0, 1, 0)),
    ("top", (0, 1, 0), (1, 0, 0), (0, 0, 1)),
    ("bottom", (0, 0, 1), (1, 0, 0), (0, 0, -1)),
]
# island slots in the 0..1 square: a 3x2 grid of 0.32 squares
SLOTS = [(0.01, 0.01), (0.34, 0.01), (0.67, 0.01),
         (0.01, 0.34), (0.34, 0.34), (0.67, 0.34)]
ISLAND = 0.32


def build_cube(broken: bool) -> str:
    verts: list[tuple[float, float, float]] = []
    uvs: list[tuple[float, float]] = []
    faces: list[tuple[list[int], list[int]]] = []

    for fi, (_name, o, du, dv) in enumerate(CORNERS):
        o, du, dv = np.array(o, float), np.array(du, float), np.array(dv,
                                                                     float)
        corners3 = [o, o + du, o + du + dv, o + dv]
        vi = []
        for c in corners3:
            verts.append(tuple(float(x) for x in c))
            vi.append(len(verts))

        ox, oy = SLOTS[fi]
        s = ISLAND
        if broken and fi == 3:
            s = ISLAND / 3.0                      # 3x less texel density
        quad = [(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)]
        if broken and fi == 4:
            quad = [(0.0, 0.0), (0.25, 0.0), (0.25, 1.0), (0.0, 1.0)]  # 4:1
        if broken and fi == 2:
            quad = quad[::-1]                     # flipped winding
        ti = []
        for (qu, qv) in quad:
            u, v = ox + qu * s, oy + qv * s
            if broken and fi == 5:
                u += 1.0                          # outside the 0..1 square
            uvs.append((u, v))
            ti.append(len(uvs))
        faces.append((vi, ti))

    lines = [f"# cube_{'broken' if broken else 'clean'}.obj",
             "# generated by examples/make_assets.py", "usemtl cube"]
    for v in verts:
        lines.append(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}")
    for t in uvs:
        lines.append(f"vt {t[0]:.6f} {t[1]:.6f}")
    for vi, ti in faces:
        lines.append("f " + " ".join(f"{a}/{b}" for a, b in zip(vi, ti)))
    return "\n".join(lines) + "\n"


def tile_texture(seam: bool) -> Image.Image:
    """Periodic by construction: sines at integer frequencies wrap
    exactly. The 'seam' version darkens the last rows/columns — the
    classic result of painting on a texture without wrapping."""
    y, x = np.mgrid[0:SIZE, 0:SIZE].astype(float) / SIZE
    v = (0.5
         + 0.22 * np.sin(2 * math.pi * 3 * x)
         + 0.18 * np.cos(2 * math.pi * 2 * y)
         + 0.10 * np.sin(2 * math.pi * 5 * (x + y)))
    v = np.clip(v, 0, 1)
    if seam:
        v[:, -12:] *= 0.55
        v[-12:, :] *= 0.55
    img = (np.stack([v, v * 0.92, v * 0.8], axis=2) * 255).astype(np.uint8)
    return Image.fromarray(img)


def normal_texture(mangled: bool) -> Image.Image:
    """A dome-ish normal map: real unit vectors, encoded the standard
    way. The mangled version is what happens when a normal map is
    treated as a picture — gamma applied, so the vectors stop being unit
    length and the lighting is quietly wrong everywhere."""
    row, x = np.mgrid[0:SIZE, 0:SIZE].astype(float) / (SIZE - 1) * 2 - 1
    # Image rows increase DOWNWARD, so surface-up is -row. Writing the
    # normal's Y straight from the row index produces a DirectX-convention
    # map (green dark at the top of a bump); negating gives OpenGL
    # (+Y up), which is what this asset claims to be — and what
    # test_normal_convention_is_identified checks the detector against.
    y = -row
    inside = x ** 2 + y ** 2 < 0.81
    nx = np.where(inside, x, 0.0)
    ny = np.where(inside, y, 0.0)
    nz = np.sqrt(np.maximum(1.0 - nx ** 2 - ny ** 2, 1e-6))
    n = np.stack([nx, ny, nz], axis=2)
    n /= np.linalg.norm(n, axis=2, keepdims=True)
    enc = (n + 1.0) / 2.0
    if mangled:
        enc = enc ** (1 / 2.2)                    # sRGB'd: vectors ruined
    return Image.fromarray((enc * 255).astype(np.uint8))


def banded_roughness() -> Image.Image:
    y, x = np.mgrid[0:SIZE, 0:SIZE].astype(float) / SIZE
    v = 0.35 + 0.25 * np.sin(2 * math.pi * 2 * x) * np.cos(2 * math.pi * y)
    v = np.round(v * 6) / 6                       # 6 levels: quantised
    return Image.fromarray((np.clip(v, 0, 1) * 255).astype(np.uint8), "L")


if __name__ == "__main__":
    HERE.mkdir(parents=True, exist_ok=True)
    (HERE / "cube_clean.obj").write_text(build_cube(False), encoding="utf-8")
    (HERE / "cube_broken.obj").write_text(build_cube(True), encoding="utf-8")
    tile_texture(False).save(HERE / "tile_clean.png")
    tile_texture(True).save(HERE / "tile_seam.png")
    normal_texture(False).save(HERE / "normal_ok.png")
    normal_texture(True).save(HERE / "normal_bad.png")
    banded_roughness().save(HERE / "rough_banded.png")
    print(f"wrote 7 assets to {HERE}")
